import console{ Print }; // importa entidade de Print
// Definição das variáveis
// É colocado por padrão um "valor morto" ao final de um array
// Então list1 é na verdade = [1, 2, 3, 4, 5, 0]
array[int] list1 = [1, 2, 3, 4, 5]; // cria array de ints
array[float] list2[10]; // cria array de floats com tamanho 10
int i = 0;
int val;

~ATH(val = list1[i]){ // vai pegando valores de list1 até achar 0
    ~ATH(){} EXECUTE( Print{i + ": " + val} );
} EXECUTE (NULL);
THIS->DIE(); // Finalizar

